[package]
name = "code-lines"
version = "0.1.0"
authors = ["Xydez <thexydez@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
clap = "3.0.0-beta.2"
term_size = "0.3.2"
