[package]
name = "code-lines"
description = "Counts the lines of code you have written"
version = "0.1.0"
authors = ["Xydez <thexydez@gmail.com>"]
edition = "2018"

[dependencies]
walkdir = "2.3"
clap = { version = "3.0", features = ["cargo"] }
term_size = "1.0.0-beta1"
